edison.coffee
Signed-off-by: Florin Sarbu <florin@resin.io>
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-edison/2)
=> edison.coffee: Fix networking options

.gitmodules, layers/meta-resin-edison/conf/samples/bblayers.conf.sample
=> Switch to docker

CHANGELOG.md, layers/meta-resin-edison/conf/samples/local.conf.sample
=> Improve build disk usage

CHANGELOG.md, layers/meta-resin-edison/conf/samples/local.conf.sample
Connects to resin-os/meta-resin#137-replace-SUPERVISOR-TAG
@telphan @floion @petrosagg
=> Replace SUPERVISOR_TAG by TARGET_TAG on resin-edison

CHANGELOG.md, layers/meta-resin-edison/conf/samples/local.conf.sample
Connects to resin-os/meta-resin#128-debug-image
@telphan @floion @petrosagg
=> Replace RESIN_STAGING_BUILD by DEBUG_IMAGE on resin-edison

.gitmodules, edison.coffee
This implements resin-os/resin-yocto-scripts#31
Signed-off-by: Eugene Mirotin eugene@resin.io
@agherzan @floion
=> Update to use the simplified JSON building process on resin-edison

CHANGELOG.md, edison.coffee
=> Introduce versioning for coffee

CHANGELOG.md, edison.coffee
@agherzan @floion @shaunmulligan 
Connects to #32
=> Move config.json to resin-boot partition

CHANGELOG.md, layers/meta-resin-edison/conf/samples/local.conf.sample
@agherzan @floion 
Connects to resin-os/meta-resin#315
=> Replace DEBUG_IMAGE with DEVELOPMENT_IMAGE

CHANGELOG.md, layers/meta-resin-edison/recipes-core/images/resin-image.bbappend
@agherzan @floion 
Connects to #36
=> Provide hook to inject files in our boot partition and also inject initial config.json

layers/meta-resin-edison/recipes-core/images/resin-image.bbappend
@agherzan @floion 
Connects to #38
=> resin-image: Refactored code in common function

CHANGELOG.md, layers/meta-resin-edison/conf/samples/bblayers.conf.sample
Connects to resin-os/meta-resin#404-meta-fs-layer
@telphan @floion @petrosagg @petrosagg @michal-mazurek
=> Add meta-filesystem as we need aufs-utils on resin-edison

README.md
Connects to contributing
@telphan @floion @michal-mazurek
=> Add Contributing section on resin-edison

CHANGELOG.md
=> * Update resin-yocto-scripts to fix logging in container builds on resin-edison

CHANGELOG.md, layers/meta-resin-edison/recipes-core/systemd/systemd/watchdog.conf, layers/meta-resin-edison/recipes-core/systemd/systemd_%.bbappend, layers/meta-resin-edison/recipes-kernel/linux/linux-yocto-edison.bbappend
=> Kernel update and change the watchdog ping to 35 seconds (on the 1.X branch)

CHANGELOG.md, layers/meta-resin-edison/recipes-kernel/linux/linux-yocto-edison.bbappend
Fixes: https://github.com/resin-os/resinos/issues/185
=> Edison aufs fix master

CHANGELOG.md, layers/meta-resin-edison/recipes-kernel/linux/linux-yocto-edison.bbappend
Connected to resin-os/resinos#185
=> Edison aufs fix 1.x

CHANGELOG.md, layers/meta-resin-edison/recipes-bsp/u-boot/files/edison.env
fixes https://github.com/resin-os/resinos/issues/168
=> Set new rootfs partitions sizes

CHANGELOG.md
This pulls in the "mkdir /factory" fix.
=> meta-edison-bsp

CHANGELOG.md, layers/meta-resin-edison/recipes-core/images/resin-image.bbappend
Details in the comment in the commit itself.
=> resin-image: increase the boot partition's size to 40MB

CHANGELOG.md
Signed-off-by: Sebastian Panceac <sebastian@resin.com>
=> Updated layer meta-edison-bsp

CHANGELOG.md, layers/meta-resin-edison/recipes-kernel/linux/linux-yocto-edison.bbappend
Signed-off-by: Florin Sarbu <florin@resin.io>
=> linux-yocto-edison.bbappend: Add support for FUSE

CHANGELOG.md
Signed-off-by: Florin Sarbu <florin@resin.io>
=> meta-edison-bsp: Update to f2740e29e74ebf5e4b0a07907db5cedcb673c9b5

CHANGELOG.md
Signed-off-by: Sebastian Panceac <spanceac@resin.io>
=> Update meta-edison-bsp with reboot fix patch

layers/meta-resin-edison/recipes-bsp/u-boot/files/0002-edison-Enable-CONFIG_CMD_SETEXPR.patch, layers/meta-resin-edison/recipes-bsp/u-boot/u-boot_2015.10.bbappend
Fixes https://github.com/balena-os/balena-edison/issues/142
=> u-boot: Enable CONFIG_CMD_SETEXPR for edison

edison.coffee, layers/meta-balena-edison/conf/layer.conf, layers/meta-balena-edison/conf/samples/bblayers.conf.sample, layers/meta-balena-edison/recipes-bsp/u-boot/files/0003-add-gcc8-header.patch, layers/meta-balena-edison/recipes-bsp/u-boot/u-boot-fw-utils_2015.10.bbappend, layers/meta-balena-edison/recipes-bsp/u-boot/u-boot_2015.10.bbappend
Update meta-balena from 2.43.0 to 2.44.0
Changelog-entry: Update meta-balena from v2.43.0 to v2.44.0
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>
=> layers/meta-balena: Update to v2.44.0
